class SCSound extends GUIDevice {

  Synth synth;
  ArrayList<SCProperty> properties = new ArrayList<SCProperty>();
  int currentx;

  SCSound(String name, String synthDef, ControlP5 cp5, int left, int top) {
    super(name, cp5, left, top);
    Textlabel t = cp5.addTextlabel(name + "label")
      .setText(name.toUpperCase())
        .setPosition(left, top+ 576);
    currentx = left;
    synth = new Synth(synthDef); // nb: not created (and moking noise) until initAllProperties is called
  }

  void initAllProperties() {
    for (SCProperty p : properties) {
      p.sendValue();
    } 
    synth.create();
  }

  // a new value has been generated by the parent device
  void newValue(Device sender) {
    float value = sender.normalisedValue;
    for (SCProperty p : properties) {
      p.newValue(value);
    }
  }

  int getRight() {
    // println (name + " called getRight on scs");
    return left + 80;
  }

  int getBottom() {
    return 500;
  }

  SCProperty addProperty(
  String name, 
  float limitMax, 
  float limitMin, 
  float maxVal, 
  float minVal, 
  float value, 
  int mode)
  {
    SCProperty property = new SCProperty(this, name, cp5, currentx, top, limitMax, limitMin, maxVal, minVal, value, mode);
    properties.add(property);
    currentx = property.getRight();
    return property;
  }

  void exit() {
    synth.free();
  }

  void addAmp() {
    String name = "amp";
    float limitMax = 1;
    float limitMin = 0;
    float maxVal = 1; 
    float minVal = 0; 
    float value = 0;
    addProperty(name, limitMax, limitMin, maxVal, minVal, value, 0);
  }


  void addPan() {
    String name = "pan";
    float limitMax = 1;
    float limitMin = -1;
    float maxVal = 0.95; 
    float minVal = -0.95; 
    float value = 0;
    addProperty(name, limitMax, limitMin, maxVal, minVal, value, 0);
  }

  void bang(Device sender) {
    for (SCProperty p : properties) {
      p.bang(sender);
    }
  }
}

